[workspace]
members = ["cudd2-sys", "kure2-sys"]
resolver = "3"

[workspace.dependencies]
cudd2-sys = { path = "cudd2-sys" }
glib-sys = "0.21.0"
gmp-mpfr-sys = "1.6.5"
kure2-sys = { path = "kure2-sys" }
