[package]
name = "kure2-sys"
version = "0.1.0"
edition = "2024"

[dependencies]
cudd2-sys = { workspace = true }
gmp-mpfr-sys = { workspace = true }
kure2-lua-sys = { workspace = true }

[build-dependencies]
fs_extra = { workspace = true }
