[package]
name = "kure2-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kure2"
path = "src/main.rs"

[dependencies]
kure2 = { workspace = true }
pretty_assertions = { workspace = true }
rustyline = { workspace = true }
